################################################################################
# Copyrights Â© 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
    - title: FirstVision-EMEA
      link: docs/Introduction.md
      access: public
      groups: []
      open: true
- sections:
    - title: Release Notes
      link: docs/release-notes/Release-notes.md
      access: public
      groups: []
      open: true
      sections:
        - title: Release 2022
          link: docs/release-notes/Releases/2022/2022.md
        - title: Release 2023
          link: docs/release-notes/Releases/2023/2023.md
- sections:
    - title: API Guide
      link: docs/API-guide.md
      access: public
      groups: []
      open: true
      sections:
        - title: Getting Started
          link:
          sections:
          - title: Overview of FirstVision terminology
            link: docs/getting-started/OverviewOfFirstVisionTerminology.md
- sections:
  - title: Self Servicing
    link: /docs/Self-servicing/self-servicing.md
    access: public
    groups: []
    open: true
    sections:
    - title: Customer
      link: docs/Self-servicing/Customer/customer.md
      open: true
      sections:
        - title: Retrieve customer number
          link: docs/Self-servicing/Customer/Retrieve-customer-number.md
        - title: Update customer demographics
          link: docs/Self-servicing/Customer/Update-customer-demographics.md
        - title: Update customer user fields
          link: docs/Self-servicing/Customer/Update-customer-user-fields.md
        - title: Retrieve customer contact preferences
          link: docs/Self-servicing/Customer/Retrieve-customer-contact-preferences.md
        - title: Update contact preferences
          link: docs/Self-servicing/Customer/Update-contact-preferences.md
    - title: Account
      link: docs/Self-servicing/Account/account.md
      open: true
      sections:
        - title: Open a new account
          link: docs/Self-servicing/Account/Open-a-new-account.md
        - title: Retrieve account number using customer number
          link: docs/Self-servicing/Account/Retrieve-account-number-using-customer-number.md
        - title: Retrieve account balance information
          link: docs/Self-servicing/Account/Retrieve-account-balance-information.md
        - title: Retrieve account limits
          link: docs/Self-servicing/Account/Retrieve-account-limits.md
        - title: Retrieve payment information
          link: docs/Self-servicing/Account/Retrieve-payment-information.md
        - title: Retrieve plan information(interest and balance at plan level)
          link: docs/Self-servicing/Account/Retrieve-plan-information.md
        - title: Retrieve transaction information
          link: docs/Self-servicing/Account/Retrieve-transaction-information.md
        - title: Retrieve direct debit information
          link: docs/Self-servicing/Account/Retrieve-direct-debit-information.md
        - title: Update credit limit of account
          link: docs/Self-servicing/Account/Update-credit-limit-of-account.md
        - title: Update direct debit details
          link: docs/Self-servicing/Account/Update-direct-debit-details.md
    - title: Card
      link: docs/Self-servicing/Card/Card.md
      open: true
      sections:
        - title: Retrieve card information
          link: docs/Self-servicing/Card/Retrieve-card-information.md
        - title: Update name on card
          link: docs/Self-servicing/Card/Update-name-on-card.md
        - title: Request a replacement card
          link: docs/Self-servicing/Card/Request-a-replacement-card.md
        - title: Request a PIN reminder(through batch process)
          link: docs/Self-servicing/Card/Request-pin-reminder.md
        - title: Block a card
          link: docs/Self-servicing/Card/Block-a-card.md
        - title: Report a lost/stolen or fraudulent card
          link: docs/Self-servicing/Card/Report-a-fraudulent-card.md
- sections:
    - title: Support
      link:
      access: public
      groups: []
      sections:
        - title: Registration & Token
          link: docs/Support/Registration-and-Token.md
        - title: Error Codes
          link: docs/Support/Error-codes.md
#         - title: Deleted/Deprecated APIs
#           link: docs/Support/Deleted-deprecated-apis.md
